# Pages CMS configuration for Rising Hope Doula
# Docs: https://pagescms.org/docs/configuration
# Edit this repo at https://app.pagescms.org after installing the Pages CMS GitHub App

media:
  input: public/images
  output: /images
  categories: [image]

content:
  # Menu Links
  - name: menu
    label: Menu Links
    type: file
    path: content/menu.json
    format: json
    fields:
      - name: menuLinks
        label: Menu Links
        type: object
        list: true
        fields:
          - name: linkText
            label: Label
            type: string
            required: true
          - name: linkHref
            label: Link Path
            type: string
            required: true
  
  # Home page hero content (editable content)
  - name: home
    label: Home Page
    type: file
    path: content/home.json
    format: json
    fields:
      - name: heroHeadline
        label: Hero Headline
        type: string
        required: true
      - name: heroTagline
        label: Hero Tagline
        type: string
        required: true

  # About page content (editable content)
  - name: about
    label: About Page
    type: file
    path: content/about.json
    format: json
    fields:
      - name: heroHeadline
        label: Hero Headline
        type: string
        required: true
      - name: aboutContent
        label: About Content
        type: rich-text
        required: true
        options:
          media: false
  
  # Blog posts (MDX files in src/app/blog/)
  - name: blog
    label: Blog Posts
    type: collection
    path: src/app/blog
    format: code
    filename: "{primary}/page.mdx"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: date
        label: Date
        type: date
        required: true
      - name: author
        label: Author
        type: string
        default: Rising Hope Doula
      - name: body
        label: Content
        type: code
        options:
          language: mdx
    view:
      primary: title
      fields: [title, date]
      sort: [date, title]
      default:
        sort: date
        order: desc

  # Testimonials data (editable content)
  - name: testimonials
    label: Testimonials
    type: file
    path: content/testimonials.json
    format: json
    fields:
      - name: testimonials
        label: Testimonials
        type: object
        list: true
        fields:
          - name: quote
            label: Quote
            type: text
            required: true
          - name: author
            label: Author Name
            type: string
            required: true
          - name: context
            label: Context
            type: string
          - name: category
            label: Category
            type: select
            options:
              values:
                - Birth Support
                - Postpartum Care
                - Prenatal Education

  # Services data (editable content)
  - name: services
    label: Services
    type: file
    path: content/services.json
    format: json
    fields:
      - name: services
        label: Services
        type: object
        list: true
        fields:
          - name: name
            label: Service Name
            type: string
            required: true
          - name: description
            label: Description
            type: text
            required: true
          - name: includes
            label: What's Included
            type: string
            list: true

  # Site settings
  - name: settings
    label: Site Settings
    type: file
    path: content/settings.json
    format: json
    fields:
      - name: siteName
        label: Site Name
        type: string
        default: Rising Hope Doula
      - name: email
        label: Contact Email
        type: string
      - name: phone
        label: Phone Number
        type: string
      - name: instagram
        label: Instagram URL
        type: string
      - name: linkedin
        label: LinkedIn URL
        type: string

settings:
  content:
    merge: true
