# Pages CMS configuration for Rising Hope Doula
# Docs: https://pagescms.org/docs/configuration
# Edit this repo at https://app.pagescms.org after installing the Pages CMS GitHub App

media:
  input: public/images
  output: /images
  categories: [image]

content:
  - name: pages
    label: Pages
    type: collection
    path: content/pages
    format: yaml-frontmatter
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: body
        label: Body
        type: rich-text
    view:
      primary: title
      fields: [title, description]
      sort: [title]
      default:
        sort: title
        order: asc

  - name: posts
    label: Blog Posts
    type: collection
    path: content/posts
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: date
        label: Date
        type: date
        required: true
      - name: author
        label: Author
        type: string
      - name: published
        label: Published
        type: boolean
        default: true
      - name: body
        label: Body
        type: rich-text
    view:
      primary: title
      fields: [title, date, published]
      sort: [date, title]
      default:
        sort: date
        order: desc

settings:
  content:
    merge: true
